### ISSUE TITLE
Strange output on Kaifama304h3e

### ISSUE THREAD

**Issue by HyperDevil** [endrebjorsvik/kaifa-meter#2]
`
python3.6 reader.py
421
420
422
423
422
421
422
421
422
422
422
422
422
422
422
421
421
421
422
421
421
421
421
421
421
421
422
422
`

**Comment by endrebjorsvik** [comment]
That output looks fairly expected, given that you actually want to run only the `reader.py` script. It shows a power consumption of approximately 420 W.

However, you are not supposed to run the `reader.py` script for anything else than development/debugging. The full script is run by the `kaifa_meter` command, as described in the [README](https://github.com/endrebjorsvik/kaifa-meter/blob/master/README.md). That command point to the `cli.py` script.

How does that work for you?

**Comment by HyperDevil** [comment]
Thanks for you answer. i misinterpreted the output :) you can close this issue.
